import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { LogOut, Search, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SiteFooter } from "@/components/site-chrome";
import { actualizarEstado, iniciarSesionAdmin, listarCasos, obtenerCaso, type CasoDetalle, type CasoLista, type SesionAdmin } from "@/lib/admin-api";

export const Route = createFileRoute("/admin")({ component: Administracion });
const estados = ["RECIBIDA", "EVALUACION", "INVESTIGACION", "CERRADA"];
const sessionKey = "inppares_admin_session";

function Administracion() {
  const [sesion, setSesion] = useState<SesionAdmin | null>(null), [nombreUsuario, setNombreUsuario] = useState(""), [password, setPassword] = useState(""), [casos, setCasos] = useState<CasoLista[]>([]), [caso, setCaso] = useState<CasoDetalle | null>(null), [busqueda, setBusqueda] = useState(""), [estado, setEstado] = useState(""), [comentario, setComentario] = useState(""), [error, setError] = useState(""), [cargando, setCargando] = useState(false);
  useEffect(() => { const guardada = localStorage.getItem(sessionKey); if (guardada) setSesion(JSON.parse(guardada) as SesionAdmin); }, []);
  useEffect(() => { if (!sesion) return; setCargando(true); listarCasos(sesion.token).then(setCasos).catch((e: Error) => setError(e.message)).finally(() => setCargando(false)); }, [sesion]);
  const cerrarSesion = () => { localStorage.removeItem(sessionKey); setSesion(null); setCaso(null); setCasos([]); };
  async function entrar(e: React.FormEvent) { e.preventDefault(); setError(""); setCargando(true); try { const nueva = await iniciarSesionAdmin(nombreUsuario, password); localStorage.setItem(sessionKey, JSON.stringify(nueva)); setSesion(nueva); setPassword(""); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo iniciar sesión."); } finally { setCargando(false); } }
  async function verCaso(id: string) { if (!sesion) return; setError(""); setCargando(true); try { const detalle = await obtenerCaso(id, sesion.token); setCaso(detalle); setEstado(detalle.estado); setComentario(""); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar el caso."); } finally { setCargando(false); } }
  async function guardarEstado() { if (!sesion || !caso) return; setCargando(true); try { await actualizarEstado(caso.id, estado, comentario, sesion.token); setCaso({ ...caso, estado }); setCasos((actuales) => actuales.map((item) => item.id === caso.id ? { ...item, estado } : item)); setComentario(""); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo actualizar el estado."); } finally { setCargando(false); } }
  if (!sesion) return <Login nombreUsuario={nombreUsuario} password={password} error={error} cargando={cargando} setNombreUsuario={setNombreUsuario} setPassword={setPassword} entrar={entrar} />;
  const filtrados = casos.filter((item) => `${item.clave} ${item.resumen} ${item.estado}`.toLowerCase().includes(busqueda.toLowerCase()));
  const puedeActualizar = sesion.roles.some((rol) => rol === "ADMINISTRADOR" || rol === "COMITE_ETICA");
  return <div className="min-h-screen bg-secondary/20"><header className="border-b bg-background"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck className="size-5" /></span><div><h1 className="font-display font-semibold">Panel interno de casos</h1><p className="text-xs text-muted-foreground">{sesion.nombre} · {sesion.roles.join(", ")}</p></div></div><Button variant="outline" size="sm" onClick={cerrarSesion}><LogOut className="size-4" /> Cerrar sesión</Button></div></header><main className="mx-auto grid max-w-7xl gap-6 px-4 py-7 sm:px-6 lg:grid-cols-[23rem_1fr]"><section className="rounded-2xl border bg-card p-4 shadow-card"><Label>Buscar casos</Label><div className="relative mt-2"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Código, estado o resumen" /></div><p className="mt-4 text-xs text-muted-foreground">{filtrados.length} caso(s)</p><div className="mt-3 max-h-[65vh] space-y-2 overflow-auto pr-1">{filtrados.map((item) => <button key={item.id} onClick={() => verCaso(item.id)} className="w-full rounded-xl border p-3 text-left transition hover:border-primary hover:bg-secondary/40"><div className="flex justify-between gap-2"><span className="font-mono text-xs font-semibold">{item.clave}</span><Badge variant="secondary" className="text-[10px]">{item.estado}</Badge></div><p className="mt-2 line-clamp-2 text-sm">{item.resumen}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.creadaEn).toLocaleString("es-PE")}</p></button>)}</div></section><section className="rounded-2xl border bg-card p-5 shadow-card sm:p-7">{error && <p className="mb-5 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{cargando && <p className="mb-4 text-sm text-muted-foreground">Cargando…</p>}{caso ? <Detalle caso={caso} estado={estado} comentario={comentario} puedeActualizar={puedeActualizar} setEstado={setEstado} setComentario={setComentario} guardarEstado={guardarEstado} cargando={cargando} /> : <div className="flex min-h-80 items-center justify-center text-center text-sm text-muted-foreground">Seleccione un caso para revisar sus respuestas.</div>}</section></main><SiteFooter /></div>;
}
function Login({ nombreUsuario, password, error, cargando, setNombreUsuario, setPassword, entrar }: { nombreUsuario: string; password: string; error: string; cargando: boolean; setNombreUsuario: (v: string) => void; setPassword: (v: string) => void; entrar: (e: React.FormEvent) => void }) { return <div className="flex min-h-screen items-center justify-center bg-secondary/30 px-4"><form onSubmit={entrar} className="w-full max-w-md rounded-2xl border bg-card p-7 shadow-card"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck className="size-5" /></span><div><p className="font-display text-xl font-semibold">Acceso interno</p><p className="text-sm text-muted-foreground">Gestión confidencial de casos</p></div></div><div className="mt-7 space-y-4"><div className="space-y-2"><Label>Nombre de usuario</Label><Input autoComplete="username" value={nombreUsuario} onChange={(e) => setNombreUsuario(e.target.value)} required /></div><div className="space-y-2"><Label>Contraseña</Label><Input type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div>{error && <p className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button type="submit" className="w-full" disabled={cargando}>{cargando ? "Ingresando…" : "Ingresar al panel"}</Button></div></form></div>; }
function Detalle({ caso, estado, comentario, puedeActualizar, setEstado, setComentario, guardarEstado, cargando }: { caso: CasoDetalle; estado: string; comentario: string; puedeActualizar: boolean; setEstado: (v: string) => void; setComentario: (v: string) => void; guardarEstado: () => void; cargando: boolean }) { return <div className="space-y-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-label">Caso</p><h2 className="mt-1 font-mono text-xl font-bold">{caso.clave}</h2></div><Badge>{caso.estado}</Badge></div><dl className="grid gap-4 text-sm sm:grid-cols-2"><Dato etiqueta="Registrado" valor={new Date(caso.creadaEn).toLocaleString("es-PE")} /><Dato etiqueta="Modalidad" valor={caso.anonimo ? "Anónima" : "Con identificación"} /><div className="sm:col-span-2"><dt className="text-muted-foreground">Resumen</dt><dd className="mt-1 whitespace-pre-wrap leading-relaxed">{caso.resumen}</dd></div><Dato etiqueta="Tipos" valor={caso.tipos.join(", ") || "No especificado"} /></dl>{caso.contacto && <Bloque titulo="Datos de contacto"><dl className="grid gap-3 text-sm sm:grid-cols-3"><Dato etiqueta="Nombre" valor={caso.contacto.nombres || "—"} /><Dato etiqueta="Correo" valor={caso.contacto.correo || "—"} /><Dato etiqueta="Teléfono" valor={caso.contacto.telefono || "—"} /></dl></Bloque>}<Bloque titulo="Respuestas del formulario"><pre className="overflow-auto rounded-xl bg-secondary/60 p-4 text-xs leading-relaxed">{JSON.stringify(caso.respuestas, null, 2)}</pre></Bloque>{puedeActualizar && <Bloque titulo="Actualizar estado"><div className="grid gap-3 sm:grid-cols-[12rem_1fr_auto]"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={estado} onChange={(e) => setEstado(e.target.value)}>{estados.map((item) => <option key={item}>{item}</option>)}</select><Input value={comentario} onChange={(e) => setComentario(e.target.value)} placeholder="Comentario interno (opcional)" maxLength={1000} /><Button onClick={guardarEstado} disabled={cargando}>Guardar</Button></div></Bloque>}</div>; }
function Bloque({ titulo, children }: { titulo: string; children: ReactNode }) { return <section><h3 className="mb-3 font-display font-semibold">{titulo}</h3>{children}</section>; }
function Dato({ etiqueta, valor }: { etiqueta: string; valor: string }) { return <div><dt className="text-muted-foreground">{etiqueta}</dt><dd className="mt-1 font-medium">{valor}</dd></div>; }
